language: java

jdk:
  - oraclejdk8
  
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 4.4
  - nvm use 4.4

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - node --version

script: gradle ci --debug
